const pick=(l,cs,en)=>l==='cs'?cs:en;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function privacyContent(l,c){
  const t=(cs,en)=>pick(l,cs,en);
  const mail=`<a href="mailto:${esc(c.email)}">${esc(c.email)}</a>`;
  const heading=(cs,en)=>`<h2>${t(cs,en)}</h2>`;
  const paragraph=(cs,en)=>`<p>${t(cs,en)}</p>`;
  return `<section class="wrap prose section border-top">
    ${!c.privacyApproved?`<div class="form-notice">${t('Příjem zpráv přes webové formuláře zatím připravujeme. Kontaktovat nás můžete přímo e-mailem.','Website forms are not yet accepting enquiries. You can contact us directly by email.')}</div>`:''}
    ${heading('Kdo zpracovává vaše údaje','Who processes your data')}
    <p>${[esc(c.operator),c.companyId?t('IČO: ','Company ID: ')+esc(c.companyId):'',esc(c.address)].filter(Boolean).join('<br>')}</p>
    <p>${t('Správce údajů a autor projektu WATRA. Pro všechny dotazy a uplatnění práv napište na','The data controller and creator of WATRA. For all enquiries and requests relating to your data, contact')} ${mail}.</p>
    ${heading('Dotazy a nezávazný zájem','Enquiries and non-binding interest')}
    ${paragraph('Používáme jméno, e-mail, zvolený model a typ zájmu; případně telefon, zemi, údaje o firmě a zprávu, pokud je doplníte. Účelem je odpovědět a probrat s vámi kamna nebo spolupráci. U poptávky jde o kroky před uzavřením smlouvy na vaši žádost (čl. 6 odst. 1 písm. b GDPR); u obecného dotazu či kontaktu za firmu o náš oprávněný zájem vyřizovat korespondenci (písm. f).','We use your name, email, selected model and type of interest, plus any phone number, country, company details or message you choose to provide. We use these to respond and discuss a heater or partnership. A prospective purchase is handled as steps taken at your request before entering into a contract (GDPR Article 6(1)(b)); general enquiries and company contacts are handled under our legitimate interest in responding to correspondence (Article 6(1)(f)).')}
    ${paragraph('Povinné údaje potřebujeme, abychom mohli odpovědět. Odeslání nevytváří závaznou objednávku a nepřihlašuje vás k newsletteru. Údaje poskytujete dobrovolně.','Required fields let us respond to your enquiry. Submitting a form does not create a binding order or subscribe you to a newsletter. Providing information is voluntary.')}
    ${heading('Upozornění na zahájení prodeje','Sales launch notifications')}
    ${paragraph('V okně na úvodní stránce žádáme váš e-mail a výslovný souhlas se zprávou o zahájení prodeje a kontaktováním k vašemu zájmu o kamna WATRA (čl. 6 odst. 1 písm. a GDPR). Uložíme i znění, verzi a čas souhlasu, jazyk a zdrojovou stránku. Bez souhlasu upozornění neposíláme; web si můžete prohlížet dál.','The homepage popup asks for your email and explicit consent to a sales launch notification and contact about your interest in WATRA heaters (GDPR Article 6(1)(a)). We also keep the consent wording, version and time, language and source page. Without consent we will not send the notification; you can still browse the website.')}
    <p>${t('Souhlas kdykoli odvoláte zprávou na','You can withdraw consent at any time by writing to')} ${mail}. ${t('Stačí uvést, že už nechcete dostávat upozornění. Odvolání nemá vliv na zákonnost předchozího zpracování.','Simply tell us you no longer want notifications. Withdrawal does not affect the lawfulness of earlier processing.')}</p>
    ${heading('Jak dlouho údaje uchováváme','How long we keep data')}
    <p>${esc(l==='cs'?c.retention:(c.retentionEn||c.retention))}</p>
    ${paragraph('Údaje pro upozornění smažeme po splnění účelu nebo dříve při odvolání souhlasu, nejpozději v uvedené lhůtě. Pokud se stanete zákazníkem, údaje potřebné pro smlouvu a zákonné povinnosti mají vlastní dobu uchování; podrobnosti obdržíte při sjednání nákupu.','Notification data is deleted once its purpose has been fulfilled, or earlier when consent is withdrawn, and no later than the period above. If you become a customer, data needed for the contract and legal obligations has a separate retention period, explained when arranging the purchase.')}
    ${heading('Kdo údaje přijímá','Who receives data')}
    ${paragraph('Příjem formulářů zajišťuje Formspree, Inc. Zadané údaje ukládá do neveřejného přehledu a doručuje do naší e-mailové schránky. Zpracovává také technické údaje, například IP adresu, prohlížeč a čas odeslání, pro doručení a ochranu proti spamu. Formspree používá infrastrukturu v USA a uvádí standardní smluvní doložky jako záruku při předávání údajů.','Formspree, Inc. handles form submissions, stores them in a private dashboard and delivers them to our email inbox. It also processes technical data such as IP address, browser and submission time for delivery and spam protection. Formspree uses US infrastructure and states that it relies on standard contractual clauses as a safeguard for data transfers.')}
    <p><a href="https://formspree.io/legal/privacy-policy/">${t('Ochrana údajů ve Formspree','Formspree privacy policy')}</a> · <a href="https://formspree.io/security/">${t('Zabezpečení a předávání údajů','Security and data transfers')}</a></p>
    ${paragraph('Na provozu se dále podílejí poskytovatel hostingu Cloudflare a poskytovatel naší e-mailové schránky. K poptávkám má přístup správce WATRA a služby nezbytné k jejich doručení a vyřízení. Nezveřejňujeme je ani neprodáváme. Kopii informací o zárukách při předávání si můžete vyžádat na kontaktním e-mailu.','Cloudflare provides website hosting, and our email provider handles mailbox delivery. Enquiries are accessible to the WATRA controller and services needed to deliver and handle them. We do not publish or sell them. You can request information about transfer safeguards through our contact email.')}
    ${c.crispWebsiteId?heading('Online chat','Online chat')+paragraph('Chat poskytuje Crisp a načte se až po kliknutí na Napište nám. Zpracuje vaši zprávu, případné kontaktní údaje a technické údaje potřebné pro konverzaci. Pro pokračování chatu používá funkční cookies. Dotaz vyřizujeme na stejném základě jako ostatní korespondenci. Obsah zpráv neposíláme do Google Analytics.','Crisp provides the chat and loads only when you click Chat with us. It processes your message, any contact details and technical data needed for the conversation. Functional cookies maintain the chat session. We handle your enquiry on the same basis as other correspondence. Message contents are not sent to Google Analytics.')+`<p><a href="https://crisp.chat/en/privacy/">${t('Ochrana údajů v Crisp','Crisp privacy policy')}</a></p>`:''}
    ${heading('Měření, cookies a jazyk','Analytics, cookies and language')}
    ${paragraph('Nepovinné měření návštěvnosti a reklamních kampaní spouštíme jen podle vašeho souhlasu. Značky spravujeme přes Google Tag Manager. Do měření neposíláme e-mail ani obsah formulářových polí. Sledujeme například zobrazení stránek, kliknutí na kontakt a potvrzené odeslání zájmu. Záznamy používání Clarity se na stránkách s formuláři nespouštějí.','Optional website and campaign measurement runs only according to your consent. Tags are managed through Google Tag Manager. We do not send your email or form field contents to analytics. Events can include page views, contact clicks and confirmed form submissions. Clarity session recording does not run on pages containing forms.')}
    ${paragraph('Volbu souhlasu si pamatujeme 180 dní v úložišti prohlížeče. Ručně zvolený jazyk ukládáme do nezbytné cookie na jeden rok. Údaje kampaně můžeme podle souhlasu uchovat po dobu relace. Odmítnutí nepovinného měření nebrání odeslání formuláře; volbu můžete změnit v patičce.','Your consent preference is remembered for 180 days in browser storage. A manually selected language is stored in an essential cookie for one year. Campaign information may be stored for the session according to consent. Rejecting optional measurement does not prevent form submission; you can change your choice in the footer.')}
    <button class="button outline" data-cookie-settings>${t('Nastavení cookies','Cookie settings')}</button>
    ${heading('Vaše práva','Your rights')}
    ${paragraph('Za podmínek GDPR můžete žádat přístup k údajům, opravu, výmaz, omezení zpracování a přenositelnost. Proti zpracování na základě oprávněného zájmu můžete vznést námitku. Souhlas můžete odvolat. Poptávky nepoužíváme k automatizovanému rozhodování s právními nebo obdobně významnými účinky.','Subject to the GDPR conditions, you can request access, correction, deletion, restriction and portability. You can object to processing based on legitimate interests and withdraw consent. Enquiries are not used for automated decision-making with legal or similarly significant effects.')}
    <p>${t('Pro uplatnění práv napište na','To exercise your rights, email')} ${mail}. ${t('Stížnost můžete podat u','You may lodge a complaint with the')} <a href="https://uoou.gov.cz/">${t('Úřadu pro ochranu osobních údajů','Czech Office for Personal Data Protection')}</a>.</p>
    <p class="small">${t('Aktualizováno 10. září 2026.','Updated 10 September 2026.')}</p>
  </section>`;
}
